#precisa subir todas as aplicações
version: '3.7'
services:
  config-server:
    container_name: config-server
    build: ./server-config
    ports: 
      - 8881:8881
    environment:
      spring.cloud.config.server.git.uri: https://github.com/Michelletxr/service-config
      server.port: 8881
    restart: unless-stopped
    networks:
      - microsservices
  registry-server:
    container_name: registry-server
    build: ./registry-server
    ports: 
      - 8761:8761
    environment:
      spring.config.import: optional:configserver:http://config-server:8881
      server.port: 8761
    depends_on: 
      - config-server
    restart: unless-stopped
    networks:
      - microsservices
    
  gateway-server:
    container_name: gateway-server
    build: ./gateway-server
    ports: 
      - 8080:8080
    depends_on: 
      - config-server
      - registry-server
    environment:
      eureka.client.serviceUrl.defaultzone: http://registry-server:8761/eureka
      spring.config.import: optional:configserver:http://config-server:8881
    restart: unless-stopped
    networks:
      - microsservices

  # lib-app:
  #   container_name: lib-app
  #   build: ./livraria
  #   container_name: lib-app
  #   ports: 
  #     - 8761:8761
  #   environment:
  #     spring.config.import: optional:configserver:http://config-server:8881
  #     server.port: 8761
  #   depends_on: 
  #     - config-serverj
  #   restart: unless-stopped
  #   networks:
  #     - microsservices
  

networks:
  microsservices:
    name: microsservices_net

